//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geoex.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GARDNER DENVER 2000 \r\n\r\nNOTAS:")]
        public string GARDNERDENVER2000 {
            get {
                return ((string)(this["GARDNERDENVER2000"]));
            }
            set {
                this["GARDNERDENVER2000"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GARDNER DENVER 15W\r\n\r\nNOTAS:")]
        public string GARDNERDENVER15W {
            get {
                return ((string)(this["GARDNERDENVER15W"]));
            }
            set {
                this["GARDNERDENVER15W"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MAYHEW 1000\r\n\r\nNOTAS:")]
        public string MAYHEW1000 {
            get {
                return ((string)(this["MAYHEW1000"]));
            }
            set {
                this["MAYHEW1000"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MIDWAY 15M\r\n\r\nNOTAS:")]
        public string MIDWAY15M {
            get {
                return ((string)(this["MIDWAY15M"]));
            }
            set {
                this["MIDWAY15M"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IR CYCLON RO 300\r\n\r\nNOTES:")]
        public string IRCYCLONRO300 {
            get {
                return ((string)(this["IRCYCLONRO300"]));
            }
            set {
                this["IRCYCLONRO300"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUCYRUSERIE 22\r\n\r\nNOTAS:")]
        public string BUCYRUSERIE22 {
            get {
                return ((string)(this["BUCYRUSERIE22"]));
            }
            set {
                this["BUCYRUSERIE22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BUCYRUSERIE 36L\r\n\r\nNOTAS:")]
        public string BUCYRUSERIE36L {
            get {
                return ((string)(this["BUCYRUSERIE36L"]));
            }
            set {
                this["BUCYRUSERIE36L"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INGERSOLLRAND 1\r\n\r\nNOTES:")]
        public string INGERSOLLRAND1 {
            get {
                return ((string)(this["INGERSOLLRAND1"]));
            }
            set {
                this["INGERSOLLRAND1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INGERSOLLRAND 2\r\n\r\nNOTAS:")]
        public string INGERSOLLRAND2 {
            get {
                return ((string)(this["INGERSOLLRAND2"]));
            }
            set {
                this["INGERSOLLRAND2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SULLAIR\r\n\r\nNOTAS:")]
        public string SULLAIR {
            get {
                return ((string)(this["SULLAIR"]));
            }
            set {
                this["SULLAIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NCA\r\n\r\nNOTAS:")]
        public string NCA {
            get {
                return ((string)(this["NCA"]));
            }
            set {
                this["NCA"] = value;
            }
        }
    }
}
